# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tt_user', '0003_auto_20180712_1716'),
        ('tt_goods', '0002_auto_20180717_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_goods.GoodsDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_user.User')),
            ],
        ),
    ]
