# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsdetail',
            name='pic',
            field=models.ImageField(upload_to='goods'),
        ),
    ]
