# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 08:59
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_goods', '0002_auto_20180717_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsdetail',
            name='content',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
