# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_goods', '0003_goodsdetail_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='pic_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='goodstype',
            name='pic_url',
            field=models.TextField(default=''),
        ),
    ]
