# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_goods', '0004_auto_20180726_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_url', models.TextField(default='')),
                ('banner_pic', models.TextField(default='')),
            ],
        ),
    ]
