# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tt_user', '0003_auto_20180712_1716'),
        ('tt_goods', '0002_auto_20180717_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_goods.GoodsDetail')),
            ],
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('expiredDate', models.DateTimeField()),
                ('oIsPay', models.BooleanField(default=False)),
                ('orderState', models.CharField(max_length=2)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('address', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_user.User')),
            ],
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tt_order.OrderInfo'),
        ),
    ]
