# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tt_order', '0003_auto_20180717_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='orderState',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
